name: Test CI

on:
#  push:
#    branches: [master]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pio
          pip install -r requirements.txt

#      - name: Lint project
#        run: flake8 .

      - name: Testing
        run: python manage.py test